### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Synneva**
Updated name in README to match new format (and become familiar with branching)

### CODE REVIEW

**Comment by fjodoin** [comment]
@Synneva Perfect! Make sure to put a short description; a Sprint 1 requirement is that we include meaningful descriptions.

**Comment by Synneva** [comment]
Aight sorry, wasn't sure if I should

**Comment by fjodoin** [comment]
No worries! Its a learning curve for everyone; i just understood an hour ago (._. )

**Comment by fjodoin** [comment]
@Synneva Go ahead and add a description to the Pull Request; i will merge it right after

**Pull request merged**
